# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: factorial.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'factorial.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x61\x63torial.proto\"\x1d\n\x10\x46\x61\x63torialRequest\x12\t\n\x01n\x18\x01 \x01(\x05\"&\n\x11\x46\x61\x63torialResponse\x12\x11\n\tfactorial\x18\x01 \x01(\x03\x32\x46\n\x10\x46\x61\x63torialService\x12\x32\n\tCalculate\x12\x11.FactorialRequest\x1a\x12.FactorialResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'factorial_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACTORIALREQUEST']._serialized_start=19
  _globals['_FACTORIALREQUEST']._serialized_end=48
  _globals['_FACTORIALRESPONSE']._serialized_start=50
  _globals['_FACTORIALRESPONSE']._serialized_end=88
  _globals['_FACTORIALSERVICE']._serialized_start=90
  _globals['_FACTORIALSERVICE']._serialized_end=160
# @@protoc_insertion_point(module_scope)
